# Generated by Django 2.2.2 on 2019-07-16 13:42

from django.db import migrations, models
from blog.models import BlogPage


def migrate_read_time(apps, schema_editor):
    blogs = BlogPage.objects.filter(read_time__isnull=True)
    for blog in blogs:
        blog.save()


def unmigrate_read_time(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='read_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RunPython(migrate_read_time, unmigrate_read_time),
    ]
