# Generated by Django 2.2.2 on 2019-06-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('blog', '0002_blogindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='featured_blog',
            field=models.ForeignKey(blank=True, help_text='Featured blog item', null=True, on_delete='CASCADE', related_name='+', to='wagtailcore.Page', verbose_name='Feature blog section'),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='featured_blog_title',
            field=models.CharField(blank=True, help_text='Feature blog title', max_length=255, null=True),
        ),
    ]
