# Generated by Django 2.2.2 on 2019-06-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190624_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='featured_blog',
            field=models.ForeignKey(blank=True, help_text='Featured blog item', null=True, on_delete='CASCADE', related_name='+', to='blog.BlogPage', verbose_name='Feature blog section'),
        ),
    ]
