# Generated by Django 2.2.2 on 2019-06-24 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190624_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='featured_blog_title',
        ),
    ]
